development:
  adapter: mysql2
  encoding: utf8
  database: lama_development
  pool: 5
  username: root
test:
  adapter: mysql2
  encoding: utf8
  database: lama_test
  pool: 5
  username: root
production: